Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

        public DbSet<Department> Departments { get; set;}
        public DbSet<Employee> employees { get; set;}
        public DbSet<Customer> Customers { get; set; }

    }
}

Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Display(Name ="Employee Name")]
        [Required]
        public string Cust_Name { get; set; }

        [Display(Name = "Employee Email")]
        [Required]
        [EmailAddress(ErrorMessage ="Email address is not valid!")]
        public string Cust_Email { get; set; }

        [Display(Name = "Employee Address")]
        [Required]
        [MaxLength(100,ErrorMessage ="Max char can't be more than 100!")]
        public string Cust_Address { get; set; }

        [Display(Name = "Employee Mobile Number")]
        [Required]
        [RegularExpression("^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$", ErrorMessage ="Inavlid mobile number!")]
        public string Mobile { get; set; }

    }
}

Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Models
{
    public class Department
    {
        public int Id { get; set; }
        public string DName { get; set; }
      
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Department Department { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CRUD_EFW.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CustomerController.cs
using CRUD_EFW.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext DbContext;
        public CustomerController(ApplicationDbContext DbContext)
        {
            this.DbContext = DbContext;
        }

        public IActionResult Index()
        {
            List<Customer> Cust = DbContext.Customers.ToList();
            return View(Cust);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Customer cust)
        {
            if (ModelState.IsValid)
            {
                DbContext.Customers.Add(cust);
                DbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(cust);
            }
        }
        public IActionResult Delete(int id)
        {
            var cust = DbContext.Customers.SingleOrDefault(e => e.Id == id);
            if (cust != null)
            {
                DbContext.Customers.Remove(cust);
                DbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
       
        public IActionResult Edit(int id)
        {
            var cust = DbContext.Customers.SingleOrDefault(e => e.Id == id);
            return View(cust);
        }
        [HttpPost]
        public IActionResult Edit(Customer cust)
        {
            DbContext.Customers.Update(cust);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD_EFW.Models;
using Microsoft.EntityFrameworkCore;

namespace CRUD_EFW.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext DbContext;
        public EmployeeController(ApplicationDbContext DbContext)
        {
            this.DbContext = DbContext;
        }
        public IActionResult Index()
        {
            List<Department> departments = DbContext.Departments.ToList();
            return View(departments);
        }
        public IActionResult EmployeeList(int Id)
        {
            List<Employee> Employees = DbContext.employees.Where(e => e.Department.Id==Id).ToList();
            return View(Employees);
        }
        
    }
}

Controllers/HomeController.cs
using CRUD_EFW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_EFW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Customer/Create.cshtml
@model CRUD_EFW.Models.Customer
@{
}
<div class="row">
    <div class="col-6 offset-3">
        <form asp-action="Create" asp-controller="Customer" method="post">
            <div class="form-group">
                <label asp-for="Cust_Name"></label>
                <input asp-for="Cust_Name" class="form-control" />
                <span asp-validation-for="Cust_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cust_Email"></label>
                <input asp-for="Cust_Email" class="form-control" />
                <span asp-validation-for="Cust_Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cust_Address"></label>
                <input asp-for="Cust_Address" class="form-control" />
                <span asp-validation-for="Cust_Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>
</div>

Views/Customer/Edit.cshtml
@model CRUD_EFW.Models.Customer
@{
}

<div class="row">
    <div class="col-6 offset-3">
        <form asp-action="Edit" asp-controller="Customer" method="post">
            <div class="form-group">
                <input type="hidden" asp-for="Id"/>
                <label asp-for="Cust_Name"></label>
                <input asp-for="Cust_Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Cust_Email"></label>
                <input asp-for="Cust_Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Cust_Address"></label>
                <input asp-for="Cust_Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Mobile"></label>
                <input asp-for="Mobile" class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>
</div>

Views/Customer/Index.cshtml
@model IEnumerable<CRUD_EFW.Models.Customer>
@{
}
<a asp-action="Create" asp-controller="Customer" class="btn btn-outline-danger">Create</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Cust_Name</th>
                <th>Cust_Email</th>
                <th>Cust_Address</th>
                <th>Mobile</th>
                <th>Action</th>

            </tr>
        </thead>
        @foreach (var cust in Model)
        {
            <tr>
                <td>@cust.Id</td>
                <td>@cust.Cust_Name</td>
                <td>@cust.Cust_Email</td>
                <td>@cust.Cust_Address</td>
                <td>@cust.Mobile</td>
                <td><a asp-action="Edit" asp-controller="Customer" asp-route-id="@cust.Id">Edit</a>|| 
                    <a asp-action="Delete" asp-controller="Customer" asp-route-id="@cust.Id" onclick="return confirm('Are you sure to delete this record?')">Delete</a>
                       </td>

            </tr>
        }
    </table>

Views/Employee/EmployeeList.cshtml
@model IEnumerable<CRUD_EFW.Models.Employee>
@{
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>EmailId</th>
            <th>Mobile</th>
            

        </tr>
    </thead>
    @foreach (var emp in Model)
    {
        <tr>
            <td>@emp.Id</td>
            <td>@emp.Name</td>
            <td>@emp.Email</td>
            <td>@emp.Mobile</td>
          
        </tr>
    }
</table>

Views/Employee/Index.cshtml
@model IEnumerable<CRUD_EFW.Models.Department>
@{
}


<table class="table table-bordered">

    <tr>

        <th>Department</th>

    </tr>
    @foreach (var dpt in Model)
    {
        <tr>
            <td>
                <a asp-action="EmployeeList" asp-controller="Employee" asp-route-Id="@dpt.Id">
                    @dpt.DName
                </a>
            </td>


        </tr>
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_EFW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_EFW</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CRUD_EFW - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>